### ISSUE TITLE
without sdk,how can i get imu data and depth infomation?

### ISSUE THREAD

**Issue by xiang-ao-data** [stereolabs/zed-opencv-native#11]
hi, i am trying to use zed2 on my raspberry pi 4. without zed sdk,i can get image from the camera by using your sample code.but how can i get the imu data and depth infomation

**Comment by obraun-sl** [comment]
Hi,
To get images and IMU data from the ZED, you can use the following open source repository : 
https://github.com/stereolabs/zed-open-capture

You won't have the depth information since it's calculated on the host by the ZED SDK.
