### ISSUE TITLE
[Zed mini] Inconsistency of Calibration File Format

### ISSUE THREAD

**Issue by ycvision** [stereolabs/zed-opencv-native#16]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I currently have two Zed mini cameras. However, I noticed that they come with calibration files of different format. One has the following format:
```
[LEFT_CAM_2K]
fx=1547.39
fy=1546.96
cx=1116.98
cy=613.638
k1=-0.0386674
k2=0.0304795
k3=-0.0237575
k4=0.0167972
```
and the other one is
```
[LEFT_CAM_2K]
fx=1400.19
fy=1399.14
cx=1090.34
cy=628.647
k1=-0.173705
k2=0.0272811
p1=0.000103475
p2=0.000166726
k3=0
```
The problem here is that using the script `python/zed_opencv_native.py` cannot produce the correctly dewarped results for the videos recorded by the Zed mini which has the first calibration format (4 radial distortion coefficients). The other one was dewarped just fine.

I wonder if different camera models need to be used?

### Steps to Reproduce

`python python/zed_opencv_native.py <serial_number>`

### Expected Result

Correctly dewarped results.

### Actual Result

Incorrectly dewarped results.

### ZED Camera model

ZED Mini

### Environment

```shell
Firmware version of both Zed minis: 1523
```

**Comment by adujardin** [comment]
We updated the calibration process to improve precision and are now using a fish eye model (depending on the hardware).
This requires an update of the code, we plan to add this feature but in the meantime here are some pointers to update it yourself if needed;
The standard `stereoRectify` function [here](https://github.com/stereolabs/zed-opencv-native/blob/master/python/zed_opencv_native.py#L121) and `initUndistortRectifyMap` should be replaced by the [fisheye ones](https://docs.opencv.org/3.4/db/d58/group__calib3d__fisheye.html#gac1af58774006689056b0f2ef1db55ecc) when a new calibration file is detected
