### ISSUE TITLE
VIDEOIO ERROR: V4L: index 0 is not correct!

### ISSUE THREAD

**Issue by bobbylark** [stereolabs/zed-opencv-native#2]
Hi i am not able to complete the download of the data from my camera.
`~/zed-opencv-native/build$` ./ZED_Opencv_Native 10026114
Calibration file found. Loading...
 Camera Matrix L: 
[700.9869995117188, 0, 631.0770263671875;
 0, 700.9869995117188, 364.4280090332031;
 0, 0, 1]

 Camera Matrix R: 
[699.3270263671875, 0, 639.64599609375;
 0, 699.3270263671875, 364.1019897460938;
 0, 0, 1]

 Camera Matrix L: 
[669.175190437979, 0, 631.2688369750977, 0;
 0, 669.175190437979, 365.062629699707, 0;
 0, 0, 1, 0]

 Camera Matrix R: 
[669.175190437979, 0, 631.2688369750977, 42158.03699759268;
 0, 669.175190437979, 365.062629699707, 0;
 0, 0, 1, 0]

VIDEOIO ERROR: V4L: index 0 is not `correct!`

**Comment by mesimolnar** [comment]
If you have any other cameras in the system, you have to change the index of the camera. E.g. I am working with a jetson tx2 dev kit board and here my zed cam is de /dev/video1 . See your cam list in your system.
