### ISSUE TITLE
Resolution unable to be adjusted

### ISSUE THREAD

**Issue by alecgao066** [stereolabs/zed-opencv-native#7]
The resolution of my ZED Camera is unable to be adjusted using OPEN CV on Raspberry Pi. There are black bars on the side of the images if the resolution is larger than 1344x376.

I set resolution here:
![code](https://user-images.githubusercontent.com/43340637/63325641-6c2e9b00-c2df-11e9-9e2d-4780d1cdbc63.JPG)

When I set resolution to 1280x720, the image is like this.
![1280x720](https://user-images.githubusercontent.com/43340637/63325670-78b2f380-c2df-11e9-91fa-2946ab10a270.jpg)

When I set resolution to 1920x1080, the image is like this.
![1920x1080](https://user-images.githubusercontent.com/43340637/63325677-7b154d80-c2df-11e9-9e75-16766d95fadf.jpg)

When I set resolution to 2208x1242, the image is like this.
![2208x1242](https://user-images.githubusercontent.com/43340637/63325683-7ea8d480-c2df-11e9-85f3-08ee11757e20.jpg)

When I set resolution to 672x376, the image is like this.
![672x376](https://user-images.githubusercontent.com/43340637/63325689-81a3c500-c2df-11e9-9565-41dc7855cc04.jpg)

**Comment by ghassenWalha** [comment]
I have the same exact problem

**Comment by ghassenWalha** [comment]
@alecgao066  I would be so appreciative if you told me how you solved the issue

**Comment by obraun-sl** [comment]
Make sure it's indeed the zed that is captured by cv2.VideoCapture. You might need to change the index depending on the number of camera on your Pi. 
Check also that the size of left_right_image[0] is the same as image_size.

**Comment by yuvrajbhaia** [comment]
hey, was wondering if there is any update or any work around the given problem?
